[package]
name = "rust_workbench"
version = "1.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/rust_workbench.rs"
doctest = false

[dependencies]
anyhow.workspace = true
async-process.workspace = true
db.workspace = true
editor.workspace = true
gpui.workspace = true
language.workspace = true
lsp.workspace = true
paths.workspace = true
project.workspace = true
serde.workspace = true
serde_json.workspace = true
text.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true

[dev-dependencies]
futures.workspace = true
gpui = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
